version: 1.0.3

images:
  backend: ghcr.io/ken-leparisiendelenfer/alma-conduit-backend:d0c1c3c00c5204de27664b8eb9e08dc45db7cb95
  frontend: ghcr.io/ken-leparisiendelenfer/alma-conduit-frontend:d0c1c3c00c5204de27664b8eb9e08dc45db7cb95
