version: 1.0.1

images:
  backend: ghcr.io/alma-hiring/devops-hiring-test-ken-leparisiendelenfer-backend:577b29cdb0ee1e9f992a731321ba777aa1b89b4f
  frontend: ghcr.io/alma-hiring/devops-hiring-test-ken-leparisiendelenfer-frontend:577b29cdb0ee1e9f992a731321ba777aa1b89b4f
